spring:
  application:
    name: petmatch-community

  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/petmatch_community
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-plataform: roh.hibernate.dialect.MariaDBDialect

server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
